name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Verify systemd units
        run: |
          systemd-analyze verify \
            ./c0pin-performance.service \
            ./c0pin-aggressive.service

      - name: Clean build
        run: make clean

      - name: Rebuild
        run: make
